- name: variables of file level
  hosts: localhost
  become: yes
  vars_files:
  - varfiles.yaml
  tasks:
  - name: print the given information
    ansible.builtin.debug:
      msg: "i am {{name}} from {{place}}"
