- name: variables from argument passing level
  hosts: localhost
  become: yes
  tasks:
  - name: get information from args
    ansible.builtin.debug:
      msg: "Hi {{person}}, good {{wishes}}"

  # pass the values from outside,through command -e person=mamatha -e wishes=morning