- name: default value
  hosts: localhost
  become: yes
  tasks:
  - name: print default value
    ansible.builtin.debug:
      msg: " Hi, {{wishes | default ('Good Morning') }}"

# here i am giving variable "wishes=Morning"as default

- name: upper case
  hosts: localhost
  become: yes
  vars:
    name: "i am mamatha"
  tasks:
  - name: print upper case
    ansible.builtin.debug:
      msg: "{{name | upper}}"

- name: lower case
  hosts: localhost
  become: yes
  vars:
    name: "I AM MAMATHA"
  tasks:
  - name: print lower case
    ansible.builtin.debug:
      msg: "{{name | lower}}"

- name: max and min numbers
  hosts: localhost
  become: yes
  vars:
    numbers: [ 30,40,72,85 ]
  tasks:
  - name: print maximum number
    ansible.builtin.debug:
      msg: "max number is: {{numbers | max}}, min number is: {{numbers | min}}"