- name: install packages
  hosts: node
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.dnf:
      name: "{{ item}}"
      state: latest
    loop:
    - nginx
    - mysql
    - postfix
  # i want to install mysql not others,refer below code

- name: install packages
  hosts: web
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.dnf:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop:
    - { name: 'mysql', state: 'latest'} # item
    - { name: 'nginx', state: 'absent'}
    - { name: 'postfix', state: 'absent'}