- name: install packages
  hosts: node
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.dnf:
      name: "{{ item}}"
      state: latest
  - name: start and enable the services
    ansible.builtin.service:
      name: "{{ item }}"
      state: started
      enabled: yes
    loop:
    - nginx
    - mysql
    - postfix
    
      
        