- name: install packages
  hosts: node
  become: yes
  tasks:
    - name: install packages
      ansible.builtin.dnf:
        name: "{{ item}}"
        state: latest
      loop:
      - nginx
      - mysql
      - postfix